// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SuperNova.Erp.Base.Domain.Utils;
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Models;

public partial class ErrorLog : EntityBase
{
    public long IdLog { get; set; }

    public DateTime Date { get; set; }

    public string LogonName { get; set; }

    public string AppSource { get; set; }

    public short Type { get; set; }

    public string Message { get; set; }

    public string AdditionalInformation { get; set; }
}