// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SuperNova.Erp.Base.Domain.Utils;
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Models;

public partial class Intento : EntityBase
{ 
    public int Id { get; set; }

    public int DeportistaId { get; set; }

    public string TipoIntento { get; set; }

    public int Peso { get; set; }

    public int? NumeroIntento { get; set; }

    public virtual Deportista Deportista { get; set; }
}