// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SuperNova.Erp.Base.Domain.Utils;
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Models;

public partial class User : EntityBase
{
    public int UserId { get; set; }

    public string LogonName { get; set; }

    public string Password { get; set; }

    public virtual ICollection<UserToken> UserTokens { get; set; } = new List<UserToken>();
}