// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SuperNova.Erp.Base.Domain.Utils;
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Models;

public partial class UserToken : EntityBase
{
    public int IdToken { get; set; }

    public int UserId { get; set; }

    public string JwtToken { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public virtual User user { get; set; }
}